version: '3'
services:
    rundeck:
        container_name: rundeck
        build:
          context: rundeck
          args:
            RUNDECK_IMAGE: ${RUNDECK_IMAGE:-rundeck/rundeck:3.3.10}
        links:
          - mysql
        environment:
            RUNDECK_GRAILS_URL: http://localhost:4440
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:mariadb://mysql/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
            RUNDECK_SERVER_ADDRESS: 0.0.0.0
            RUNDECK_FEATURE_UINEXT_NAME: uiNext
            RUNDECK_FEATURE_UINEXT_ENABLED: 'true'
        ports:
          - 4440:4440
    mysql:
        container_name: mysql
        image: mysql:8
        expose:
          - 3306
        cap_add:
          - SYS_NICE  # CAP_SYS_NICE reduces error messages in console
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=rundeck
          - MYSQL_USER=rundeck
          - MYSQL_PASSWORD=rundeck
    client:
      container_name: client
      build:
        context: client
      environment:
        CONFIG_FILE: import.yml
        RUNDECK_URL: http://rundeck:4440
        RUNDECK_API_URL: http://localhost:4440
        RUNDECK_TOKEN: u5gJoKU3NpS6IC4lFmPQFfDkUlZnQOXp
      volumes:
        - shared-volume:/rundeck-cli/data/keys/
        - ./data/user.aclpolicy:/rundeck-cli/data/user.aclpolicy
    node:
      container_name: node1
      build:
        context: node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
        - KEY_FILE=/configuration/id_rsa
      volumes:
        - shared-volume:/configuration/
    node2:
      container_name: node2
      build:
        context: node-demo
      ports:
         - "22"
      environment:
        - SSHD_PORT=22
        - KEY_FILE=/configuration/id_rsa
      volumes:
        - shared-volume:/configuration/
    ciao:
        container_name: ciao
        image: brotandgames/ciao
        ports:
          - '3000:3000'
        environment:
          - 'BASIC_AUTH_USERNAME=admin'
          - 'BASIC_AUTH_PASSWORD=admin'
          - 'CIAO_WEBHOOK_ENDPOINT_RUNDECK=http://rundeck:4440/api/38/webhook/fgl0TfHvIDLVXWUXtYDE9Ctxw7dctaxw#Server_Diagnostics_and_Recovery'

volumes:
  shared-volume:
